= Metamer

Metamer is a testing application and test suite which covers all of RichFaces 4 components and it is able to display them in different templates (tables, accordion, ui:repeat, ...)

== Metamer Maven Structure 

Metamer consists of root module and three submodules:

* root - parent for application, ftest and ftest-legacy
* application - Java-EE application
* ftest - functional test suite using Selenium 2, contains most of tests
* ftest-legacy - legacy functional test suite using Selenium 1

== Metamer Application Structure

Metamer is Maven based web application which can be deployed onto Wildfly 8 (and possibly any other Java EE container) and Tomcat 7 and 8.

Source code is available at https://github.com/richfaces/richfaces-qa/tree/master/metamer[GitHub].

=== JSF Page per Component/Feature

* Templates
** configurable nesting of templates using various container components:
** root: +webapp/templates/template.xhtml+
** templates:
*** plain
*** iteration - a4jRepeat, hDataTable, richDataTable...
*** panels -  richPanel, richTabPanel, richTogglePanel, richAccordion...
* Page Parts
** +template.xhtml+ - nesting mechanism (see above)
** +header.xhtml+ - contains general controls
** +footer.xhtml+ - contains output of VersionBean
* Customization per component (ui:insert in +template.xhtml+):
** outOfTemplateBefore - usually contains additional controls for advanced features of components which can’t be covered by customization of attribute values
** content - contains component nested in all configured templates
** outOfTemplateAfter - as for outOfTemplateBefore, usually contains attribute list
* Attributes
** attributes for each component are bound directly from page using following notation:
*** +#{componentBean.attributes[‘attributeName’].value}+
*** where +attributes+ stands for +class Attributes extends Map<String, Attribute>+
*** attributes are loaded to map from richfaces’s +faces-config.xml+
*** attributes can have predefined enumeration values using +ComponentBean.properties+ files
* Separation
** each component has own package (named like Bean for given component) for component samples
** in each package there is:
*** +list.xhtml+ - the links to all samples
*** +simple.xhtml+ - default component usage (not compulsory)
*** +{feature}.xhtml+ - feature sample

=== Managed Beans

* per component (and some per component/feature)
* bean.* packages
* +RichBean+
** serves common functionality for general tests (actions, action listeners)
* +TemplatesBean+
** serves list of templates for user session
* +PhasesBean+
** holds the list of phases which request goes through
** phases provided by +RichPhaseListener+
* +VersionBean+
** provides set of runtime and browser versions
** output on each Metamer page => can be copied to JIRA’s environment

=== Model

* provides models collections for iteration
* loaded from XMLs using JAXB
* model.* packages
* exposed in bean Model

=== Additional Resources

* any other resources are located under +webapp/resources/*+

== Building and running Metamer

=== Building Metamer
Metamer can be built in several profiles to satisfy compatibility with various runtimes and JSF implementations. To build the application, run bash script +build.sh+ in root directory of Metamer. This script generates several WAR archives with application in directory +application/target+ which can be used in various scenarios:

* metamer-glassfish31.war - to deploy on GlassFish 3.1
* metamer-jbas71.war - to deploy on Wildfly 8
* metamer-tomcat7-mojarra.war - with bundled JSF Mojarra reference implementation to deploy on Tomcat 7
* metamer-tomcat7-myfaces.war - with bundled JSF MyFaces to deploy on Tomcat 7
* metamer-tomee15.war - to deploy on TomEE 1.5

To build the application with one specific profile run +mvn clean install -DskipTests -P{profileName}+ where +profileName+ can be found in https://github.com/richfaces/richfaces-qa/blob/master/pom.xml[pom.xml] in root directory. Created WAR file will be located in +application/target+ folder.

=== Deploying Metamer

To deploy the application just copy the WAR file into server deployment folder. Optionally, you can import the project into IDE (Eclipse, JBDS,...) and deploy directly from IDE. This is particularly useful when you need to do a lot of changes and re-deploy often.

=== Changing JSF implementation

To change the JSF implementation you can build Metamer with either a script mentioned above or a pre-set profile named +war-tomcat7-myfaces+

== Functional Test Development

=== Running a test
* switch to metamer/ftest directory and run +mvn clean verify -PprofileName -Dtest=testName -Dtemplates=templateName [-Dbrowser=browserName]+ 
** profileName is a name of a container you want to use, see pom.xml in parent for their names
*** e.g. +-Pwildfly-remote-8-1+
** testName is a name of a specific test to run
*** e.g. +-Dtest=TestEditor+ for all tests in TestEditor class or +-Dtest=TestEditor#testRendered+ to run just one method
*** regular expression can be used, for instance +-Dtest=TestA*+ will run all test classes which name begins with 'TestA'
** omit +-Dtest+ if you want to run all tests
** templateName is one or more of the templates such as plain, richPanel, a4jRepeat, uiRepeat
*** list of all templates used in tests can be found in `AbstractMetamerTest` in the annotation `@Templates` over the field *template*  
*** all templates are case insensitive and have aliases (can be found/edited in `org.richfaces.tests.metamer.Template`)
*** to run tests in:
**** all templates: use `*` or `all`
**** no template (default value): use `plain`, `no`, `none` or do not use the *templates* property
**** more templates concurrently: use `+` for separating the templates, e.g. `popup+accordion+edt` (ExtendedDataTable in Accordion in PopupPanel)
**** more templates separately: use `,` for separating the templates, e.g. `accordion,popup,popup+edt`. Each test in test suite will be executed in each specified template(s) (if it can run in such template).
** browser will set the used browser, download necessary driver binaries, download and extract the browser binary (linux, firefox and non-Jenkins environment only), download and extract EAP when some `jbosseap-managed` profile activated and will kill container's and driver's processes before testing. If the Jenkins environment is detected, then everything to download will be downloaded from the network drive. If the browser option is not specified, system's Firefox will be used for testing and none of the previous tasks will be done.
*** browserName is case-insensitive name of the browser to be used. Supported browsers are Internet Explorer (`browserName` contains `ie`, `internetExplorer` or `explorer`), Chrome (`browserName` contains `cr` or `chrome`), Firefox (browserName contains `ff` or `firefox`). If the browser is Firefox, then the name can be followed by a number, which will be used to specify browser's version, which will be downloaded and used for testing (linux and non-Jenkins environment only).
**** some examples:
***** `-Dbrowser=ff` to run tests with system's Firefox browser.
***** `-Dbrowser=cr` to run tests with system's Chrome browser.
***** `-Dbrowser=ie9` to run tests with system's IE browser (the version `9` will be ignored) 
***** `-Dbrowser=ff30` to run tests with downloaded Firefox 30.

=== Debugging a test
* set a breakpoint in code
* to run debugging from terminal simply add another switch +-Dmaven.surefire.debug test+

=== Creating new tests
** create or modify .xhtml in the +application/src/main/webapp/components+, this is the facelet which will be loaded in the test
** create .java test class in the package for the component, in the +ftest/src/test/java/...+
** we are using Arquillian Graphene 2, tests have these specifics:
*** tests should extend +AbstractWebDriverTest+, have a look at: method with +@Deployment+ annotation, +@Drone WebDriver browser+ injection point, +@ArquillianResource contextRoot+, +@BeforeMethod loadPage+
*** we are using Page Object pattern, have a look at @Page annotation
*** we are using Page Fragments pattern, have a look at @FindBy annotations, for more information see Graphene documentation
 
=== Creating issue reproducers in Metamer

* when creating new facelet for the issue, create it under affected component with the name of issue number (e.g. +rf-15422.xhtml+)
** the newly created issue should also contain a steps to reproduce the issue, e.g. +<r:panel header="steps to reproduce">1. blah blah <br /> 2. blah blah</r:panel>+
** list the newly created facelet also in the list.xhtml, together with the issue description and reference
* create also a test class with the same name (e.g. +TestRF15422.java+) under the package for the affected component
* annotate test method with:

** +@Test(groups = "Future")+

** +@IssueTracking(value = { "https://issues.jboss.org/browse/RF-15422" })+

* try to reuse existing backing beans, otherwise create new ones in the package +application/src/main/java/org/richfaces/tests/metamer/bean/issues+
* make a comment in the JIRA issue what facelet reproduce the issue, and also steps to reproduce it

=== About annotations
In tests there are several important annotations we use:

* +@Test(groups = "Future")+
** adding a test into future group means this test is currently failing and is expected to pass once the fix will be done
** there is a separate Jenkins job running future tests only
** once a test passing, change this to +@Test+ only

* +@IssueTracking("https://issues.jboss.org/browse/RF-007")+
** IssueTracking means the test is tracking an issue and is usually used along with future tests
** this helps us to determine why the test marked as future fails, once the test is all right this annotation changes to +@RegressionTest("https://issues.jboss.org/browse/RF-007")+

* +@RegressionTest("https://issues.jboss.org/browse/RF-007")+
** this indicates that the test was once tracking some issue and that issue was already resolved
** if such a test fails we know that it is a regression problem immediately

* +@Templates(value = {"templateName"}, exclude = {"anotherTemplateName"})+
** this indicates in which templates you want or you do not want the test to be execute
** test will not run when it is not executed with correct template
** beware that it work only for templates listed in +@Templates+ annotation in +AbstractMetamerTest+

* +@UseForAllTests+
** this indicates that the field will be used as injection point in all tests from the class where it is placed to all classes extending it
** all test methods in this hierarchy can run multiple times each time with different value injected to the annotated field (values and how to get them is specified in annotation parameters, see the javadoc for more informations)

* +@UseWithField+
** this indicates that the test method will be used with a field to which the values specified in annotation attributes will be injected
** uses the first field which will be found in class hierarchy from current class to the `Object` class
** such marked test method can run multiple times each time with different value injected to the field which is using (field, values and how to get them is specified in annotation parameters, see the javadoc for more informations)

* +@Uses+
** this is helper annotation for using multiple `@UseWithField` annotations in a single test method

== Metamer RichFaces Bug Report Guidelines

. Find if JIRA already exists (use filters to ease your work)
. File new RF/RFPL project Bug. RF is for bugs related to RichFaces (e.g. malfunctioning component). RFPL is for Metamer related problems (e.g. create/fix tests, update app dependency etc.).
** choose components (probably component-* for specific component bug)
** choose affects versions
** for Metamer:
*** Environment - use Metamer’s footer with detailed runtime, browser and libs info
*** Steps to Reproduce, e.g.:
a. open http://localhost:8080/metamer/faces/components/richList/simple.xhtml
b. set @first=5
c. set @rows=10
d. EXPECTED: to show 10 items
e. ACTUAL: shows 15 items
*** sometimes no need for Description
*** screenshot may be needed
** otherwise:
*** Description with code sample (Bean + JSF)
*** use {code} for formatting code samples and stack traces (see JIRA formating rules for more info on formating)
*** eventually provide specific version control revision or WAR directly
