package org.richfaces.tests.metamer.ftest.richTooltip;

import org.richfaces.tests.metamer.ftest.attributes.AttributeEnum;

public enum TooltipAttributes implements AttributeEnum {
    attached,
    data,
    dir,
    direction,
    execute,
    followMouse,
    hideDelay,
    hideEvent,
    horizontalOffset,
    jointPoint,
    lang,
    layout,
    limitRender,
    mode,
    onbeforedomupdate,
    onbeforehide,
    onbeforeshow,
    onbegin,
    onclick,
    oncomplete,
    ondblclick,
    onhide,
    onmousedown,
    onmousemove,
    onmouseout,
    onmouseover,
    onmouseup,
    onshow,
    render,
    rendered,
    showDelay,
    showEvent,
    status,
    style,
    styleClass,
    title,
    target,
    verticalOffset,
    zindex,
    
}
